name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'

      - name: Build executables
        run: |
          chmod +x build.sh
          ./build.sh
          mkdir -p releases
          mv fsr_* releases/
          ls releases/          

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: releases/fsr_*
          token: ${{ secrets.PAT_TOKEN }}          